<?php
require_once __DIR__ . '/functions.php';
$userId = requireUser();

$queries = [
    'weekly' => "SELECT t.track_id, t.title, t.audio_url, t.cover_image, ar.artist_name, COUNT(sh.stream_id) AS metric FROM stream_history sh JOIN tracks t ON t.track_id = sh.track_id JOIN albums al ON al.album_id = t.album_id JOIN artists ar ON ar.artist_id = al.artist_id WHERE sh.played_at >= CURRENT_TIMESTAMP - INTERVAL 7 DAY GROUP BY t.track_id, t.title, t.audio_url, t.cover_image, ar.artist_name ORDER BY metric DESC, t.title LIMIT 10",
    'trending' => "SELECT t.track_id, t.title, t.audio_url, t.cover_image, ar.artist_name, SUM(sh.played_at >= CURRENT_TIMESTAMP - INTERVAL 7 DAY) AS recent_plays, SUM(sh.played_at >= CURRENT_TIMESTAMP - INTERVAL 28 DAY) AS four_week_plays FROM stream_history sh JOIN tracks t ON t.track_id = sh.track_id JOIN albums al ON al.album_id = t.album_id JOIN artists ar ON ar.artist_id = al.artist_id WHERE sh.played_at >= CURRENT_TIMESTAMP - INTERVAL 28 DAY GROUP BY t.track_id, t.title, t.audio_url, t.cover_image, ar.artist_name ORDER BY recent_plays DESC, four_week_plays DESC, t.title LIMIT 10",
    'played' => "SELECT t.track_id, t.title, t.audio_url, t.cover_image, ar.artist_name, COUNT(sh.stream_id) AS metric FROM stream_history sh JOIN tracks t ON t.track_id = sh.track_id JOIN albums al ON al.album_id = t.album_id JOIN artists ar ON ar.artist_id = al.artist_id GROUP BY t.track_id, t.title, t.audio_url, t.cover_image, ar.artist_name ORDER BY metric DESC, t.title LIMIT 10",
    'liked' => "SELECT t.track_id, t.title, t.audio_url, t.cover_image, ar.artist_name, COUNT(f.user_id) AS metric FROM favorites f JOIN tracks t ON t.track_id = f.track_id JOIN albums al ON al.album_id = t.album_id JOIN artists ar ON ar.artist_id = al.artist_id GROUP BY t.track_id, t.title, t.audio_url, t.cover_image, ar.artist_name ORDER BY metric DESC, t.title LIMIT 10",
    'rated' => "SELECT t.track_id, t.title, t.audio_url, t.cover_image, ar.artist_name, AVG(r.rating) AS average_rating, COUNT(r.user_id) AS rating_count FROM ratings r JOIN tracks t ON t.track_id = r.track_id JOIN albums al ON al.album_id = t.album_id JOIN artists ar ON ar.artist_id = al.artist_id GROUP BY t.track_id, t.title, t.audio_url, t.cover_image, ar.artist_name HAVING COUNT(r.user_id) >= 2 ORDER BY average_rating DESC, rating_count DESC, t.title LIMIT 10",
    'recent' => "SELECT DISTINCT t.track_id, t.title, t.audio_url, t.cover_image, ar.artist_name, MAX(sh.played_at) AS last_played FROM stream_history sh JOIN tracks t ON t.track_id = sh.track_id JOIN albums al ON al.album_id = t.album_id JOIN artists ar ON ar.artist_id = al.artist_id WHERE sh.user_id = :user_id GROUP BY t.track_id, t.title, t.audio_url, t.cover_image, ar.artist_name ORDER BY last_played DESC LIMIT 10",
];
$sections = [];
foreach ($queries as $name => $sql) {
    $stmt = $pdo->prepare($sql);
    $stmt->execute($name === 'recent' ? ['user_id' => $userId] : []);
    $sections[$name] = $stmt->fetchAll();
}
$newReleases = $pdo->query("SELECT al.album_id, al.title, al.cover_image, al.release_date, ar.artist_name FROM albums al JOIN artists ar ON ar.artist_id = al.artist_id WHERE al.release_date IS NOT NULL ORDER BY al.release_date DESC LIMIT 8")->fetchAll();
$ratedAlbums = $pdo->query("SELECT al.album_id, al.title, al.cover_image, ar.artist_name, AVG(r.rating) average_rating, COUNT(r.user_id) rating_count FROM albums al JOIN artists ar ON ar.artist_id = al.artist_id JOIN tracks t ON t.album_id = al.album_id JOIN ratings r ON r.track_id = t.track_id GROUP BY al.album_id, al.title, al.cover_image, ar.artist_name HAVING COUNT(r.user_id) >= 2 ORDER BY average_rating DESC, rating_count DESC LIMIT 8")->fetchAll();
$popularArtists = $pdo->query("SELECT ar.artist_id, ar.artist_name, ar.profile_image, COUNT(DISTINCT af.user_id) follower_count, COUNT(DISTINCT sh.stream_id) stream_count FROM artists ar LEFT JOIN albums al ON al.artist_id = ar.artist_id LEFT JOIN tracks t ON t.album_id = al.album_id LEFT JOIN stream_history sh ON sh.track_id = t.track_id LEFT JOIN artist_follows af ON af.artist_id = ar.artist_id GROUP BY ar.artist_id, ar.artist_name, ar.profile_image ORDER BY stream_count DESC, follower_count DESC LIMIT 8")->fetchAll();
$ratedArtists = $pdo->query("SELECT ar.artist_id, ar.artist_name, AVG(r.rating) average_rating, COUNT(r.user_id) rating_count FROM artists ar JOIN albums al ON al.artist_id = ar.artist_id JOIN tracks t ON t.album_id = al.album_id JOIN ratings r ON r.track_id = t.track_id GROUP BY ar.artist_id, ar.artist_name HAVING COUNT(r.user_id) >= 2 ORDER BY average_rating DESC, rating_count DESC LIMIT 8")->fetchAll();
$genres = $pdo->query('SELECT genre_id, genre_name FROM genres ORDER BY genre_name')->fetchAll();
$playlistsStmt = $pdo->prepare('SELECT playlist_id, playlist_name FROM playlists WHERE user_id = :user_id ORDER BY playlist_name');
$playlistsStmt->execute(['user_id' => $userId]);
$playlists = $playlistsStmt->fetchAll();
$favoriteCountStmt = $pdo->prepare('SELECT COUNT(*) FROM favorites WHERE user_id = :user_id');
$favoriteCountStmt->execute(['user_id' => $userId]);
$favoriteCount = (int)$favoriteCountStmt->fetchColumn();
$message = $_SESSION['success'] ?? $_SESSION['error'] ?? '';
$messageType = isset($_SESSION['error']) ? 'error' : 'success';
unset($_SESSION['success'], $_SESSION['error']);
?>
<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>PulseFlow Dashboard</title><link rel="stylesheet" href="../frontend/user-dashbord.css"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"><style>
.feature-bar{display:flex;gap:10px;flex-wrap:wrap;margin:14px 0 24px}.feature-bar a,.genre-pill{padding:9px 13px;border:1px solid var(--border);border-radius:999px;color:var(--text-muted);text-decoration:none}.feature-bar a:hover,.genre-pill:hover{color:var(--text-white);border-color:var(--spotify-green)}.metric{color:var(--text-muted);font-size:.8rem}.card-actions{display:flex;gap:8px;align-items:center}.card-actions form{display:inline}.small-action{background:none;border:0;color:var(--text-muted);cursor:pointer;padding:4px}.small-action:hover{color:var(--spotify-green)}.alert{padding:12px 16px;border-radius:10px;margin-bottom:16px;background:rgba(30,215,96,.14)}.alert.error{background:rgba(239,68,68,.16)}.genre-list{display:flex;gap:10px;flex-wrap:wrap}.album-row{display:flex;gap:14px;align-items:center;padding:10px 0;border-bottom:1px solid var(--border);color:inherit;text-decoration:none}.album-row img{width:56px;height:56px;object-fit:cover;border-radius:8px}.empty{color:var(--text-muted)}
+</style></head><body><div class="main-container"><aside class="sidebar"><div class="logo"><i class="fab fa-spotify"></i><span>PulseFlow</span></div><nav class="nav-links"><a href="user-dashbord.php" class="active"><i class="fas fa-home"></i> Home</a><a href="search.php"><i class="fas fa-search"></i> Search</a><a href="favorites.php"><i class="fas fa-heart"></i> Favorites <span class="list-count"><?php echo $favoriteCount; ?></span></a><a href="playlists.php"><i class="fas fa-book"></i> Playlists</a><a href="subscriptions.php"><i class="fas fa-crown"></i> Subscription</a><a href="../backend/logout.php"><i class="fas fa-sign-out-alt"></i> Logout</a></nav><div class="library-box"><div class="library-header"><h3>Your Playlists</h3><a class="icon-btn" href="playlists.php" aria-label="Manage playlists"><i class="fas fa-plus"></i></a></div><?php foreach ($playlists as $playlist): ?><a class="list-item" href="playlist.php?id=<?php echo (int)$playlist['playlist_id']; ?>"><span><?php echo e($playlist['playlist_name']); ?></span></a><?php endforeach; ?><?php if (!$playlists): ?><p class="empty">Create your first playlist.</p><?php endif; ?></div></aside><main class="main-content"><header class="top-nav"><div class="nav-arrows"><i class="fas fa-chevron-left"></i><i class="fas fa-chevron-right"></i></div><div class="user-actions"><a class="badge-btn premium-btn" href="subscriptions.php">Explore Premium</a><span class="user-icon"><i class="fas fa-user"></i></span></div></header><?php if ($message): ?><div class="alert <?php echo $messageType === 'error' ? 'error' : ''; ?>"><?php echo e($message); ?></div><?php endif; ?><section class="greeting-section"><h2>Welcome back, <?php echo e($_SESSION['username'] ?? 'User'); ?></h2><div class="feature-bar"><a href="recently-played.php">Recently Played</a><a href="followed-artists.php">Followed Artists</a><a href="recommendations.php">Recommended For You</a></div></section>
+<?php foreach ([['weekly','Top 100 Songs This Week'],['trending','Trending Songs'],['played','Most Played'],['liked','Most Liked'],['rated','Highest Rated Songs'],['recent','Recently Played']] as [$key,$title]): ?><section class="content-section"><div class="section-header"><h2><?php echo $title; ?></h2><?php if ($key === 'recent'): ?><a href="recently-played.php">View all</a><?php endif; ?></div><div class="card-grid"><?php foreach ($sections[$key] as $track): ?><article class="card"><a href="track.php?id=<?php echo (int)$track['track_id']; ?>"><img src="<?php echo e($track['cover_image'] ?: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=400&q=80'); ?>" alt="<?php echo e($track['title']); ?> cover"></a><h4><?php echo e($track['title']); ?></h4><p><?php echo e($track['artist_name']); ?></p><div class="card-actions"><button class="small-action play-track" data-track-id="<?php echo (int)$track['track_id']; ?>" data-audio-url="<?php echo e($track['audio_url']); ?>" data-title="<?php echo e($track['title']); ?>" data-artist="<?php echo e($track['artist_name']); ?>" title="Play"><i class="fas fa-play"></i></button><form action="api.php" method="post"><input type="hidden" name="csrf_token" value="<?php echo e(csrfToken()); ?>"><input type="hidden" name="action" value="favorite"><input type="hidden" name="track_id" value="<?php echo (int)$track['track_id']; ?>"><input type="hidden" name="redirect" value="user-dashbord.php"><button class="small-action" title="Favorite"><i class="fas fa-heart"></i></button></form><?php if (isset($track['metric'])): ?><span class="metric"><?php echo (int)$track['metric']; ?> plays</span><?php elseif (isset($track['average_rating'])): ?><span class="metric">★ <?php echo number_format((float)$track['average_rating'], 1); ?></span><?php endif; ?></div></article><?php endforeach; ?><?php if (!$sections[$key]): ?><p class="empty">No data yet. Start listening to build this section.</p><?php endif; ?></div></section><?php endforeach; ?>
+<section class="content-section"><div class="section-header"><h2>New Releases</h2></div><div><?php foreach ($newReleases as $album): ?><a class="album-row" href="album.php?id=<?php echo (int)$album['album_id']; ?>"><img src="<?php echo e($album['cover_image'] ?: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=200&q=80'); ?>" alt=""><span><strong><?php echo e($album['title']); ?></strong><br><span class="metric"><?php echo e($album['artist_name']); ?> · <?php echo e($album['release_date']); ?></span></span></a><?php endforeach; ?></div></section><section class="content-section"><div class="section-header"><h2>Browse by Genre</h2></div><div class="genre-list"><?php foreach ($genres as $genre): ?><a class="genre-pill" href="genre.php?id=<?php echo (int)$genre['genre_id']; ?>"><?php echo e($genre['genre_name']); ?></a><?php endforeach; ?></div></section></main></div><footer class="music-player"><div class="now-playing"><img id="player-cover" src="https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=200&q=80" alt="Current track cover"><div class="track-info"><h5 id="player-title">Select a track</h5><p id="player-artist">Nothing playing</p></div></div><div class="player-controls"><div class="control-buttons"><button class="small-action" id="player-play" title="Play or pause"><i class="fas fa-circle-play main-play"></i></button></div><div class="progress-bar-container"><span id="player-current">0:00</span><input id="player-progress" type="range" min="0" max="100" value="0" aria-label="Playback progress"><span id="player-duration">0:00</span></div></div><audio id="audio-player" preload="metadata"></audio></footer><script>
+const audio=document.getElementById('audio-player'),progress=document.getElementById('player-progress');let currentTrack=0,streamSent=false;const formatTime=s=>{s=Math.floor(s||0);return Math.floor(s/60)+':'+String(s%60).padStart(2,'0')};document.querySelectorAll('.play-track').forEach(b=>b.addEventListener('click',()=>{if(!b.dataset.audioUrl){alert('This demo track has no audio file yet.');return}currentTrack=b.dataset.trackId;streamSent=false;audio.src=b.dataset.audioUrl;document.getElementById('player-title').textContent=b.dataset.title;document.getElementById('player-artist').textContent=b.dataset.artist;audio.play().catch(()=>{})}));document.getElementById('player-play').addEventListener('click',()=>audio.paused?audio.play():audio.pause());audio.addEventListener('timeupdate',()=>{progress.value=audio.duration?(audio.currentTime/audio.duration)*100:0;document.getElementById('player-current').textContent=formatTime(audio.currentTime);if(currentTrack&&!streamSent&&audio.currentTime>=3){streamSent=true;fetch('api.php',{method:'POST',body:new URLSearchParams({csrf_token:'<?php echo e(csrfToken()); ?>',action:'stream',track_id:currentTrack,duration_played:String(Math.floor(audio.currentTime)),session_id:'<?php echo e(session_id()); ?>'})})}});audio.addEventListener('loadedmetadata',()=>document.getElementById('player-duration').textContent=formatTime(audio.duration));progress.addEventListener('input',()=>{if(audio.duration)audio.currentTime=(progress.value/100)*audio.duration});
+</script></body></html>
*** End Patch