<?php
require_once __DIR__ . '/functions.php';
$userId = requireUser(); $playlistId = filter_input(INPUT_GET, 'id', FILTER_VALIDATE_INT) ?: 0;
$playlistStmt = $pdo->prepare('SELECT playlist_id, playlist_name, is_public, user_id FROM playlists WHERE playlist_id = :id AND (user_id = :user_id OR is_public = 1)'); $playlistStmt->execute(['id' => $playlistId, 'user_id' => $userId]); $playlist = $playlistStmt->fetch();
if (!$playlist) { http_response_code(404); exit('Playlist not found.'); }
$stmt = $pdo->prepare('SELECT pt.track_order, t.track_id, t.title, t.duration_seconds, ar.artist_name FROM playlist_tracks pt JOIN tracks t ON t.track_id = pt.track_id JOIN albums al ON al.album_id = t.album_id JOIN artists ar ON ar.artist_id = al.artist_id WHERE pt.playlist_id = :id ORDER BY pt.track_order IS NULL, pt.track_order, t.title'); $stmt->execute(['id' => $playlistId]); $tracks = $stmt->fetchAll();
$owner = (int)$playlist['user_id'] === $userId;
$allTracks = $owner ? $pdo->query('SELECT t.track_id, t.title, ar.artist_name FROM tracks t JOIN albums al ON al.album_id = t.album_id JOIN artists ar ON ar.artist_id = al.artist_id ORDER BY t.title LIMIT 200')->fetchAll() : [];
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?php echo e($playlist['playlist_name']); ?></title><link rel="stylesheet" href="../frontend/user-dashbord.css"><style>.page{max-width:1000px;margin:auto}.panel{background:var(--bg-card);padding:24px;border-radius:14px;margin:20px 0}.row{display:flex;justify-content:space-between;padding:14px 0;border-bottom:1px solid var(--border)}.muted{color:var(--text-muted)}a{color:inherit}.inline{display:inline}</style></head><body><main class="main-content page"><p><a href="playlists.php">Playlists</a></p><section class="panel"><h1><?php echo e($playlist['playlist_name']); ?></h1><p class="muted"><?php echo $playlist['is_public'] ? 'Public' : 'Private'; ?></p><?php if ($owner): ?><form method="post" action="api.php"><input type="hidden" name="csrf_token" value="<?php echo e(csrfToken()); ?>"><input type="hidden" name="action" value="rename_playlist"><input type="hidden" name="playlist_id" value="<?php echo $playlistId; ?>"><input type="hidden" name="redirect" value="playlist.php?id=<?php echo $playlistId; ?>"><input name="playlist_name" value="<?php echo e($playlist['playlist_name']); ?>" required><button>Rename</button></form><form method="post" action="api.php"><input type="hidden" name="csrf_token" value="<?php echo e(csrfToken()); ?>"><input type="hidden" name="action" value="add_to_playlist"><input type="hidden" name="playlist_id" value="<?php echo $playlistId; ?>"><input type="hidden" name="redirect" value="playlist.php?id=<?php echo $playlistId; ?>"><select name="track_id" required><?php foreach ($allTracks as $candidate): ?><option value="<?php echo (int)$candidate['track_id']; ?>"><?php echo e($candidate['title']); ?> - <?php echo e($candidate['artist_name']); ?></option><?php endforeach; ?></select><button>Add track</button></form><?php endif; ?><?php foreach ($tracks as $track): ?><div class="row"><a href="track.php?id=<?php echo (int)$track['track_id']; ?>"><?php echo (int)$track['track_order']; ?>. <?php echo e($track['title']); ?> <span class="muted">- <?php echo e($track['artist_name']); ?></span></a><span class="muted"><?php echo (int)$track['duration_seconds']; ?> sec <?php if ($owner): ?><form class="inline" method="post" action="api.php"><input type="hidden" name="csrf_token" value="<?php echo e(csrfToken()); ?>"><input type="hidden" name="action" value="remove_from_playlist"><input type="hidden" name="playlist_id" value="<?php echo $playlistId; ?>"><input type="hidden" name="track_id" value="<?php echo (int)$track['track_id']; ?>"><input type="hidden" name="redirect" value="playlist.php?id=<?php echo $playlistId; ?>"><button>Remove</button></form><?php endif; ?></span></div><?php endforeach; ?><?php if (!$tracks): ?><p class="muted">This playlist is empty.</p><?php endif; ?></section></main></body></html>
