<?php
require_once __DIR__ . '/functions.php';
$userId = requireUser();
$queueStmt = $pdo->prepare('SELECT q.queue_id, q.queue_position, t.track_id, t.title, t.audio_url, t.cover_image, ar.artist_name, COALESCE((SELECT GROUP_CONCAT(a2.artist_name ORDER BY ta2.display_order, a2.artist_name SEPARATOR \' & \') FROM track_artists ta2 JOIN artists a2 ON a2.artist_id = ta2.artist_id WHERE ta2.track_id = t.track_id), ar.artist_name) AS artist_names FROM playback_queue q JOIN tracks t ON t.track_id = q.track_id JOIN albums al ON al.album_id = t.album_id JOIN artists ar ON ar.artist_id = al.artist_id WHERE q.user_id = :user_id ORDER BY q.queue_position, q.queue_id');
$queueStmt->execute(['user_id' => $userId]);
$queue = $queueStmt->fetchAll();
$csrf = csrfToken();
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Up Next - PulseFlow</title><link rel="stylesheet" href="../frontend/user-dashbord.css"><style>
.queue-page{max-width:980px;margin:0 auto;padding:34px 24px 120px}.queue-page h1{margin:10px 0 8px;font-size:clamp(2rem,5vw,3.6rem)}.queue-top{display:flex;justify-content:space-between;align-items:end;gap:16px;margin-bottom:26px}.muted{color:var(--text-muted)}.queue-list{display:grid;gap:10px}.queue-item{display:grid;grid-template-columns:34px 1fr auto;gap:14px;align-items:center;padding:12px 14px;background:rgba(255,255,255,.045);border:1px solid var(--border);border-radius:12px}.queue-item img{width:54px;height:54px;object-fit:cover;border-radius:8px}.queue-track{display:flex;align-items:center;gap:12px;min-width:0}.queue-track strong,.queue-track span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.queue-track span{color:var(--text-muted);font-size:.88rem;margin-top:4px}.queue-number{color:var(--spotify-green);font-weight:800;text-align:center}.queue-actions{display:flex;gap:6px}.queue-actions form{display:inline}.queue-button{border:1px solid var(--border);background:rgba(255,255,255,.06);color:var(--text-white);border-radius:8px;padding:8px 10px;cursor:pointer}.queue-button:hover{border-color:var(--spotify-green);color:var(--spotify-green)}.danger{color:#ffb4b4}.empty-queue{padding:44px 24px;text-align:center;background:rgba(255,255,255,.035);border:1px dashed var(--border);border-radius:14px}.queue-link{color:var(--spotify-green);text-decoration:none}.back{color:var(--text-muted);text-decoration:none}@media(max-width:600px){.queue-page{padding:24px 14px 120px}.queue-top{align-items:start;flex-direction:column}.queue-item{grid-template-columns:24px 1fr}.queue-actions{grid-column:2}.queue-item img{width:46px;height:46px}}
</style></head><body><main class="queue-page"><a class="back" href="user-dashbord.php">&larr; Back to your dashboard</a><div class="queue-top"><div><p class="muted">YOUR LISTENING QUEUE</p><h1>Up Next</h1><p class="muted">Tracks play in this order after your current song.</p></div><?php if($queue): ?><form method="post" action="api.php"><input type="hidden" name="csrf_token" value="<?php echo e($csrf); ?>"><input type="hidden" name="action" value="queue_clear"><input type="hidden" name="redirect" value="queue.php"><button class="queue-button danger" type="submit">Clear queue</button></form><?php endif; ?></div><?php if($queue): ?><div class="queue-list"><?php foreach($queue as $index=>$item): ?><article class="queue-item"><span class="queue-number"><?php echo $index + 1; ?></span><div class="queue-track"><img src="<?php echo e($item['cover_image'] ?: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=200&q=80'); ?>" alt=""><div><strong><?php echo e($item['title']); ?></strong><span><?php echo e($item['artist_names'] ?: $item['artist_name']); ?></span></div></div><div class="queue-actions"><form method="post" action="api.php"><input type="hidden" name="csrf_token" value="<?php echo e($csrf); ?>"><input type="hidden" name="action" value="queue_move"><input type="hidden" name="queue_id" value="<?php echo (int)$item['queue_id']; ?>"><input type="hidden" name="direction" value="up"><input type="hidden" name="redirect" value="queue.php"><button class="queue-button" type="submit" aria-label="Move up">&uarr;</button></form><form method="post" action="api.php"><input type="hidden" name="csrf_token" value="<?php echo e($csrf); ?>"><input type="hidden" name="action" value="queue_move"><input type="hidden" name="queue_id" value="<?php echo (int)$item['queue_id']; ?>"><input type="hidden" name="direction" value="down"><input type="hidden" name="redirect" value="queue.php"><button class="queue-button" type="submit" aria-label="Move down">&darr;</button></form><form method="post" action="api.php"><input type="hidden" name="csrf_token" value="<?php echo e($csrf); ?>"><input type="hidden" name="action" value="queue_remove"><input type="hidden" name="queue_id" value="<?php echo (int)$item['queue_id']; ?>"><input type="hidden" name="redirect" value="queue.php"><button class="queue-button danger" type="submit" aria-label="Remove from queue">&times;</button></form></div></article><?php endforeach; ?></div><?php else: ?><div class="empty-queue"><h2>Your queue is empty</h2><p class="muted">Add songs from Home, Search, or any track page and they will appear here.</p><a class="queue-link" href="user-dashbord.php">Find something to play</a></div><?php endif; ?></main></body></html>
