<?php
require_once __DIR__ . '/functions.php';
$userId = requireUser();
$page = $page ?? 'favorites';
$csrf = csrfToken();
$rows = [];
$title = ucfirst(str_replace('-', ' ', $page));

if ($page === 'favorites' || $page === 'recently-played') {
    $where = $page === 'favorites' ? 'f.user_id = :user_id' : 'sh.user_id = :user_id';
    $join = $page === 'favorites' ? 'JOIN favorites f ON f.track_id = t.track_id' : 'JOIN stream_history sh ON sh.track_id = t.track_id';
    $date = $page === 'favorites' ? '' : ', MAX(sh.played_at) AS last_played';
    $stmt = $pdo->prepare(trackQuery() . "$date $join WHERE $where GROUP BY t.track_id, t.title, t.audio_url, t.cover_image, al.album_id, al.title, al.cover_image, ar.artist_id, ar.artist_name ORDER BY " . ($page === 'favorites' ? 't.title' : 'last_played DESC'));
    $stmt->execute(['user_id' => $userId]); $rows = $stmt->fetchAll();
} elseif ($page === 'followed-artists') {
    $stmt = $pdo->prepare('SELECT ar.artist_id, ar.artist_name, ar.profile_image, ar.bio FROM artist_follows af JOIN artists ar ON ar.artist_id = af.artist_id WHERE af.user_id = :user_id ORDER BY ar.artist_name'); $stmt->execute(['user_id' => $userId]); $rows = $stmt->fetchAll();
} elseif ($page === 'recommendations') {
    $stmt = $pdo->prepare("SELECT t.track_id, t.title, t.cover_image, t.audio_url, ar.artist_name, COUNT(DISTINCT tg.genre_id) AS matching_genres, MAX(COALESCE(ug.genre_plays, 0)) AS genre_affinity, MAX(COALESCE(ua.artist_plays, 0)) AS artist_affinity FROM tracks t JOIN albums al ON al.album_id = t.album_id JOIN artists ar ON ar.artist_id = al.artist_id JOIN track_genres tg ON tg.track_id = t.track_id LEFT JOIN (SELECT tg2.genre_id, COUNT(*) genre_plays FROM stream_history sh2 JOIN track_genres tg2 ON tg2.track_id = sh2.track_id WHERE sh2.user_id = :genre_user_id GROUP BY tg2.genre_id) ug ON ug.genre_id = tg.genre_id LEFT JOIN (SELECT al2.artist_id, COUNT(*) artist_plays FROM stream_history sh3 JOIN tracks t2 ON t2.track_id = sh3.track_id JOIN albums al2 ON al2.album_id = t2.album_id WHERE sh3.user_id = :artist_user_id GROUP BY al2.artist_id) ua ON ua.artist_id = al.artist_id LEFT JOIN (SELECT DISTINCT track_id FROM stream_history WHERE user_id = :heard_user_id) heard ON heard.track_id = t.track_id WHERE heard.track_id IS NULL AND (ug.genre_id IS NOT NULL OR ua.artist_id IS NOT NULL) GROUP BY t.track_id, t.title, t.cover_image, t.audio_url, ar.artist_name ORDER BY artist_affinity DESC, genre_affinity DESC LIMIT 20"); $stmt->execute(['genre_user_id' => $userId, 'artist_user_id' => $userId, 'heard_user_id' => $userId]); $rows = $stmt->fetchAll();
} elseif ($page === 'subscriptions') {
    $stmt = $pdo->prepare('SELECT plan_name, start_date, end_date, status, amount FROM subscriptions WHERE user_id = :user_id ORDER BY start_date DESC'); $stmt->execute(['user_id' => $userId]); $rows = $stmt->fetchAll();
} elseif ($page === 'playlists') {
    $stmt = $pdo->prepare('SELECT p.playlist_id, p.playlist_name, p.is_public, COUNT(pt.track_id) track_count FROM playlists p LEFT JOIN playlist_tracks pt ON pt.playlist_id = p.playlist_id WHERE p.user_id = :user_id GROUP BY p.playlist_id ORDER BY p.playlist_name'); $stmt->execute(['user_id' => $userId]); $rows = $stmt->fetchAll();
}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?php echo e($title); ?> - PulseFlow</title><link rel="stylesheet" href="../frontend/user-dashbord.css"><style>.page{max-width:1000px;margin:auto}.panel{background:var(--bg-card);padding:24px;border-radius:14px;margin:20px 0}.row{display:flex;justify-content:space-between;gap:12px;align-items:center;padding:14px 0;border-bottom:1px solid var(--border)}.muted{color:var(--text-muted)}.button{background:var(--spotify-green);border:0;border-radius:20px;padding:9px 14px;font-weight:700}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:14px}.card{background:#242424;padding:14px;border-radius:10px}.card img{width:100%;aspect-ratio:1;object-fit:cover;border-radius:8px}.card h3{margin:10px 0 4px}.card p{color:var(--text-muted)}a{color:inherit}.alert{padding:12px;background:rgba(30,215,96,.15);border-radius:8px}</style></head><body><main class="main-content page"><p><a href="user-dashbord.php">Home</a></p><h1><?php echo e($title); ?></h1>
<?php if ($page === 'playlists'): ?><section class="panel"><form method="post" action="api.php"><input type="hidden" name="csrf_token" value="<?php echo e($csrf); ?>"><input type="hidden" name="action" value="create_playlist"><input type="text" name="playlist_name" placeholder="Playlist name" required><button class="button">Create playlist</button></form></section><section class="panel"><?php foreach ($rows as $row): ?><div class="row"><a href="playlist.php?id=<?php echo (int)$row['playlist_id']; ?>"><?php echo e($row['playlist_name']); ?></a><span class="muted"><?php echo (int)$row['track_count']; ?> tracks - <?php echo $row['is_public'] ? 'Public' : 'Private'; ?></span></div><?php endforeach; ?></section>
<?php elseif ($page === 'subscriptions'): ?><section class="panel"><p>Current account plan: <strong><?php echo e($_SESSION['subscription_type'] ?? 'free'); ?></strong></p><p class="muted">Choose a plan to update your account. Payment processing can be connected later.</p><form method="post" action="api.php"><input type="hidden" name="csrf_token" value="<?php echo e($csrf); ?>"><input type="hidden" name="action" value="change_subscription"><input type="hidden" name="plan" value="premium"><input type="hidden" name="redirect" value="subscriptions.php"><button class="button" type="submit">Choose Premium - $9.99/month</button></form><?php if (($_SESSION['subscription_type'] ?? 'free') === 'premium'): ?><form method="post" action="api.php"><input type="hidden" name="csrf_token" value="<?php echo e($csrf); ?>"><input type="hidden" name="action" value="change_subscription"><input type="hidden" name="plan" value="free"><input type="hidden" name="redirect" value="subscriptions.php"><button class="button" type="submit">Cancel Premium</button></form><?php endif; ?><?php foreach ($rows as $row): ?><div class="row"><span><?php echo e($row['plan_name']); ?> <span class="muted"><?php echo e($row['status']); ?></span></span><span><?php echo e($row['start_date']); ?> to <?php echo e($row['end_date'] ?: 'ongoing'); ?> - $<?php echo number_format((float)$row['amount'], 2); ?></span></div><?php endforeach; ?></section>
<?php elseif ($page === 'followed-artists'): ?><section class="grid"><?php foreach ($rows as $row): ?><article class="card"><h3><a href="artist.php?id=<?php echo (int)$row['artist_id']; ?>"><?php echo e($row['artist_name']); ?></a></h3><p><?php echo e($row['bio']); ?></p></article><?php endforeach; ?></section>
<?php else: ?><section class="grid"><?php foreach ($rows as $row): ?><article class="card"><img src="<?php echo e($row['cover_image'] ?: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=400&q=80'); ?>" alt=""><h3><a href="track.php?id=<?php echo (int)$row['track_id']; ?>"><?php echo e($row['title']); ?></a></h3><p><?php echo e($row['artist_name']); ?></p><?php if ($page === 'favorites'): ?><form method="post" action="api.php"><input type="hidden" name="csrf_token" value="<?php echo e($csrf); ?>"><input type="hidden" name="action" value="favorite"><input type="hidden" name="track_id" value="<?php echo (int)$row['track_id']; ?>"><input type="hidden" name="redirect" value="favorites.php"><button class="button">Remove favorite</button></form><?php endif; ?></article><?php endforeach; ?></section><?php endif; ?><?php if (!$rows): ?><p class="muted">Nothing here yet.</p><?php endif; ?></main></body></html>
